version: '2'
services:
  web:
   build: .
   ports:
    - "8080:8080"
   volumes:
    - .:/app
   depends_on:
    - mongo
  mongo:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    command: --smallfiles --rest --auth
